version: "3.7"

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    security_opt:
      - seccomp:unconfined
    ports:
      - 5432:5432
    networks:
      - fc-challenge-typescript

networks:
  fc-challenge-typescript:
